### ISSUE TITLE
Dataset Splits Unclear | CUB

### ISSUE THREAD

**Issue by miguelvalente** [uqzhichen/GSMFlow#2]
Hi, 

is it possible to comment on how you obtained the dataset splits, in the specific case of CUB. You mention you follow the configuration of [53] (_Good, bad an ugly_), but there are 3 different proposed splits and 2 different standard splits.

- Which split from [53] did you use?
- What is the meaning of ['train_label_new']? Is it the correspondence of image to attribute category?

BR

**Comment by miguelvalente** [comment]
The overall organization of the mat files is unclear. I see that in the _label.mat_ of the CUB dataset the _'train_idx'_ seems to share class idxs with 'test_unseen_idex'

**Comment by uqzhichen** [comment]
Hi there,

I used the data provided from https://github.com/yunlongyu/EPGN. The train_label_new correspond to the mapped labels, in other words, it maps a seen class label from the 1-200 to 1-150. The semantic vectors used here for CUB are 1024d. You can find them used in quite a few recent papers as well, e.g., Contrastive Embedding for Generalized Zero-Shot Learning, cvpr2021.

Cheers,
Zhi

**Comment by uqzhichen** [comment]
You can also refer to my the other repo, SDGZSL, where I provide the origin of the datasets. https://github.com/uqzhichen/SDGZSL

**Comment by uqzhichen** [comment]
Feel free to drop me an Email, I usually reply email quicker than here. :) zhi.chen@uq.edu.au
