### ISSUE TITLE
Missing self. ?

### ISSUE THREAD

**Issue by miguelvalente** [uqzhichen/GSMFlow#3]
Is there a self. missing? Otherwise the _train_att_ variable is never used

https://github.com/uqzhichen/GSMFlow/blob/5db88aa806b944a9753758d48a59dbf2b2eba7d2/dataset_GBU.py#L32

**Comment by miguelvalente** [comment]
Same thing with this variable. Its never used

https://github.com/uqzhichen/GSMFlow/blob/5db88aa806b944a9753758d48a59dbf2b2eba7d2/dataset_GBU.py#L60

**Comment by uqzhichen** [comment]
Hi there, 

As you can see, the variable seen_pro is used instead here as the seen class attributes. Same for training labels, train_idx is used instead as well.

This repo is not for developing an off-the-shelf system, if there are more typos in it, I feel sorry about the impect souce code.

Cheers,
Zhi

**Comment by miguelvalente** [comment]
Thanks! I understand the repo is not dev oriented. The way things are set up makes the code and mat files matching confusing. I've lost more than a couple of hours making sense of it. If anything these issues might help someone who is going through the same process! 

Nonetheless, thx for making the code for the paper public.
BR,
Miguel
