### ISSUE TITLE
mask && dropout

### ISSUE THREAD

**Issue by Xiao-lv-lol** [uqzhichen/GSMFlow#5]
Hi Zhi，

Excuse me, why did you set the hyper-parameter **dropout** to 0 in your **code**? The output of mask is always True, mask has lost its meaning!I don't find any explanation on this aspect in your paper. Could you give me some advice?

**Comment by uqzhichen** [comment]
Hi Xiao,

The mask on the perturbation noise is not necessary on all datasets. You may try different dropout rate to see the impact.

Cheers,
Zhi
